/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TaxonomyRouteImport } from './routes/taxonomy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RedirectsRouteImport } from './routes/redirects'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as BlogIdRouteImport } from './routes/blog.$id'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomyRoute = TaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectsRoute = RedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/journal': typeof JournalRouteWithChildren
  '/landing': typeof LandingRoute
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/redirects': typeof RedirectsRoute
  '/resources': typeof ResourcesRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/website': typeof WebsiteRoute
  '/blog/$id': typeof BlogIdRoute
  '/journal/$slug': typeof JournalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/journal': typeof JournalRouteWithChildren
  '/landing': typeof LandingRoute
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/redirects': typeof RedirectsRoute
  '/resources': typeof ResourcesRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/website': typeof WebsiteRoute
  '/blog/$id': typeof BlogIdRoute
  '/journal/$slug': typeof JournalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/integrations': typeof IntegrationsRoute
  '/journal': typeof JournalRouteWithChildren
  '/landing': typeof LandingRoute
  '/media': typeof MediaRoute
  '/newsletter': typeof NewsletterRoute
  '/redirects': typeof RedirectsRoute
  '/resources': typeof ResourcesRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/team': typeof TeamRoute
  '/templates': typeof TemplatesRoute
  '/website': typeof WebsiteRoute
  '/blog/$id': typeof BlogIdRoute
  '/journal/$slug': typeof JournalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/analytics'
    | '/architecture'
    | '/blog'
    | '/case-studies'
    | '/changelog'
    | '/docs'
    | '/help'
    | '/integrations'
    | '/journal'
    | '/landing'
    | '/media'
    | '/newsletter'
    | '/redirects'
    | '/resources'
    | '/seo'
    | '/settings'
    | '/taxonomy'
    | '/team'
    | '/templates'
    | '/website'
    | '/blog/$id'
    | '/journal/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/analytics'
    | '/architecture'
    | '/blog'
    | '/case-studies'
    | '/changelog'
    | '/docs'
    | '/help'
    | '/integrations'
    | '/journal'
    | '/landing'
    | '/media'
    | '/newsletter'
    | '/redirects'
    | '/resources'
    | '/seo'
    | '/settings'
    | '/taxonomy'
    | '/team'
    | '/templates'
    | '/website'
    | '/blog/$id'
    | '/journal/$slug'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/analytics'
    | '/architecture'
    | '/blog'
    | '/case-studies'
    | '/changelog'
    | '/docs'
    | '/help'
    | '/integrations'
    | '/journal'
    | '/landing'
    | '/media'
    | '/newsletter'
    | '/redirects'
    | '/resources'
    | '/seo'
    | '/settings'
    | '/taxonomy'
    | '/team'
    | '/templates'
    | '/website'
    | '/blog/$id'
    | '/journal/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRoute
  HelpRoute: typeof HelpRoute
  IntegrationsRoute: typeof IntegrationsRoute
  JournalRoute: typeof JournalRouteWithChildren
  LandingRoute: typeof LandingRoute
  MediaRoute: typeof MediaRoute
  NewsletterRoute: typeof NewsletterRoute
  RedirectsRoute: typeof RedirectsRoute
  ResourcesRoute: typeof ResourcesRoute
  SeoRoute: typeof SeoRoute
  SettingsRoute: typeof SettingsRoute
  TaxonomyRoute: typeof TaxonomyRoute
  TeamRoute: typeof TeamRoute
  TemplatesRoute: typeof TemplatesRoute
  WebsiteRoute: typeof WebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomy': {
      id: '/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof TaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirects': {
      id: '/redirects'
      path: '/redirects'
      fullPath: '/redirects'
      preLoaderRoute: typeof RedirectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchitectureRoute: ArchitectureRoute,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRoute,
  HelpRoute: HelpRoute,
  IntegrationsRoute: IntegrationsRoute,
  JournalRoute: JournalRouteWithChildren,
  LandingRoute: LandingRoute,
  MediaRoute: MediaRoute,
  NewsletterRoute: NewsletterRoute,
  RedirectsRoute: RedirectsRoute,
  ResourcesRoute: ResourcesRoute,
  SeoRoute: SeoRoute,
  SettingsRoute: SettingsRoute,
  TaxonomyRoute: TaxonomyRoute,
  TeamRoute: TeamRoute,
  TemplatesRoute: TemplatesRoute,
  WebsiteRoute: WebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
